import {VerticalBox, ScrollView, TabWidget} from "std-widgets.slint";

export component MainWindow inherits Window {
    min-width: 900px;
    min-height: 900px;

    in property <string> processes: "";

    title: "SyVibes";
    accessible-role: AccessibleRole.image;
    background: #1e1e1f;
    
    GridLayout {
        spacing: 20pt;
        padding: 10px;
        x: 8px;
        y: 17px;
        TabWidget {
            row: 0;
            col: 0;
            width: 350px;
            Tab {
                title: "Processes";
                ScrollView {
                    width: parent.width;
                    height: parent.height - 60px;
                    viewport-width: 500px;
                    viewport-height: 2000px;

                    Text {
                        x: 0px;
                        y: 0px;
                        text: root.processes;
                        font-size: 15px;
                        font-weight: 900;
                        font-family: "Comic Sans MS";
                        font-italic: true;
                    }
                }
            }
        }
    }
}
